FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .

RUN pip3 install --upgrade pip
RUN pip3 install -r requirements.txt
RUN pip3 install httpx==0.26.0 h11==0.14.0 httpcore==1.0.5

COPY . .

ENV PYTHONWARNINGS="ignore"
CMD ["flask", "--app", "main.py", "run", "--host", "0.0.0.0"]
